name: Starter workflow

on: 
  push:
    branches: 
      - main
    
 
    
  workflow_dispatch:
    
jobs:
  job1:
    name: job 1
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello NDC porto"

        
      - name: Checkout
        uses: actions/checkout@v3.0.2
