name: Starter workflow

on: 
  push:
    branches: 
      - main
  issues:
    types: [opened, reopened]
    
  schedule:
    - cron: '11 11 * * 5'
    
  workflow_dispatch:
    inputs: 
      homedrive:
        description: Add home drive
        required: true
        default: home
    
jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello NDC porto"
