name: Starter workflow

on: 
  push:
    branches: 
      - main
    
 
    
  workflow_dispatch:
    
jobs:
  job1:
    name: job 1
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello NDC porto"
      - name: Execute hello world
        run: |
          import platform
          print {platform.platform()}
        shell: python
